general:
  organization: "my-org"
  secrets_key_id: "my-aws-kms-key-id"

sites:
  ordered:
    - site1
    - site2

environments:
  default:
    name: "dev"
    domain: "example.com"
    profile_name: "default"
    region: "eu-west-1"
    permanent: true

  temporary:
    secrets:
      firebase_credentials: "base64-creds"
      mail_password: "super-secret"

default_environment: dev
