site_name       = "{{ .Site }}"
organization    = "{{ .Organization }}"
environment     = "{{ .Env }}"
firebase_creds  = "{{ .FirebaseCredentials }}"
mail_password   = "{{ .MailPassword }}"
secret_token    = "{{ .Password }}"
