site_name      = "{{ .Site }}"
organization   = "{{ .Org }}"
environment    = "{{ .Env }}"
firebase_creds = "{{ .FirebaseCreds }}"
mail_password  = "{{ .MailPassword }}"
secret_token   = "{{ .SecretToken }}"
